apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-backup
spec:
  template:
    spec:
      containers:
        - name: backup
          image: postgres:13
          env:
            - name: PGPASSWORD
              value: "testpassword"
          command: [ "sh", "-c", "pg_dump -h 10.42.0.10 -U testuser -d testdb > /backup/mydatabase_backup.sql" ]
          volumeMounts:
            - name: backup-storage
              mountPath: /backup
      restartPolicy: OnFailure
      volumes:
        - name: backup-job
          persistentVolumeClaim:
            claimName: pvc-job
  backoffLimit: 4
