# etcd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: etcd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.4
        env:
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://etcd:2379"
        ports:
        - containerPort: 2379
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: etcd
spec:
  ports:
  - port: 2379
    targetPort: 2379
  selector:
    app: etcd
